name: Transfer code to GCP VM

on:
  push:
    branches: [ main ]

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with GCP
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
      id: auth

    - name: Copy files to GCP VM
      uses: appleboy/scp-action@master
      with:
      host: [ ece461-project ]
        username: [ williamgabrielj ]
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: [ ./ ]
        target: [ ~ ]


