name: Transfer code to GCP VM

on:
  push:
    branches: [ main ]

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with GCP
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
      id: auth

    - name: Copy files to GCP VM
      uses: appleboy/scp-action@master
      with:
      host: [ ece461-project ]
        username: [ williamgabrielj ]
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: [ ./ ]
        target: [ ~ ]

name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: williamgabrielj@gmail.com
          service_account_key: ${{ secrets.gcp_sa_key }}

      - name: Deploy to Google Cloud VM
        uses: google-github-actions/deploy-cloud-run@v1
        with:
          image: gcr.io/your-project-id/your-image
          project_id: your-project-id
          zone: us-central1-a
          instance_name: your-instance-name
          source: ./path/to/files



